# -*- coding: utf-8 -*-
"""Variables and Simple Data Types

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PnNzjj8F6YFcamP9pgRdbK7X8YeKUXN7
"""

#1. Assign a message to a variable and then print the message. Then change the value
#of the variable to a new message, and print the new message
'''Dua Rajat
2/07/25
The program print message along with possible change in text'''
message = "This is my first program in python at XIM"
print(message)
message = "This message is now changed"
print(message)
print("\n")
'''2. Use a variable to represent a person’s name, and print a message to that person.
Your message should be simple, such as, “Hello Eric, would you like to learn some
Python today?”'''
'''Dua Rajat
2/07/25
The program prints message using format string concept'''
name = "Eric Saltzman"
print(f"Hello {name}, would you like to learn some Python today?")
print("\n")
"""3. Use a variable to represent a person’s name and then print that person’s name in
lowercase, uppercase, and title case."""
'''Dua Rajat
2/07/25
The program performs basic string operations'''
name = "Dua rajaT"
print(name.lower())
print(name.upper())
print(name.title())
print("\n")
"""4. Find a quote from a famous person you admire. Print the quote and the name of its
author. Your output should look something like the following, including the
quotation marks:
Albert Einstein once said, “A person who never made a
mistake never tried anything new.”"""
'''Dua Rajat
2/07/25
The program deals with the concept of complex Format string'''

quote = "Be sure you put your feet in the right place, then stand firm."
print(f'Abraham Lincoln once said, "{quote}"')
print("\n")
'''5. Repeat Q. No. 4, but this time, represent the famous person’s name using a variable
called famous_person. Then compose your message and represent it with a new
variable called message. Print your message.'''
'''Dua Rajat
2/07/25
The program deals with the concept of complex Format string'''
famous_person = "Abraham Lincoln"
quote = 'Be sure you put your feet in the right place, the stand firm.'
message = f'{famous_person} once said, "{quote}"'
print(message)
print("\n")
'''6. Use a variable to represent a person’s name, and include some whitespace
characters at the beginning and end of the name. Make sure you use each
character combination, “\t” and “\n”, at least once.
Print the name once, so the whitespace around the name is displayed. Then print
the name using each of the three stripping functions, lstrip(), rstrip(), and strip().'''
'''Dua Rajat
2/07/25
The program performs strip functions'''
name = " This person who is a \t scientist name is \n Ram Sharma "
print(name)
print(name.lstrip())
print(name.rstrip())
print(name.strip())
print("\n")
'''7. Use a variable to represent your favorite number. Then, using that variable, create
a message that reveals your favorite number. Print that message'''
'''Dua Rajat
2/07/25
The program combines number and string variables using format string concept'''
num_fav = 9
message = f"Your favorite number is {num_fav}"
print(message)

'''8. Add your name and the current date at the top of each program file as a comment.
Then write one sentence describing what the program does.'''

# from google.colab import drive
# drive.mount('/content/drive')